disabled_rules: # rule identifiers to exclude from running
    - colon
    - comma
    - control_statement
    - line_length
    - trailing_whitespace
    - identifier_name
    - function_parameter_count
    - function_body_length
excluded:
    - Pods
